In [1]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:90% !important;}
div.cell.code_cell.rendered{width:100%;}
div.input_prompt{padding:0px;}
div.CodeMirror {font-family:Consolas; font-size:12pt;}
div.text_cell_render.rendered_html{font-size:12pt;}
div.output {font-size:12pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:12pt;}
div.prompt {min-width:100px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:12pt;padding:5px;}
table.dataframe{font-size:12px;}
</style>
"""))

<b><font size="6" Color="red">ch10. "N-Dimensional Arrays 4p~6p"</font></b>

# 4절. 복사와 뷰

## 4.1 할당

In [2]:
import numpy as np
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
b = a

In [4]:
a.shape, a.ndim, id(a), type(a)

((12,), 1, 2690118237040, numpy.ndarray)

In [5]:
b.shape, b.ndim, id(b), type(b)

((12,), 1, 2690118237040, numpy.ndarray)

In [6]:
a is b

True

In [7]:
a==b

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [8]:
np.all(a==b)

True

In [10]:
b.shape = (3,4) # 할당받은 b의 shape을 수정

In [11]:
a.shape, a.ndim, id(a), type(a)

((3, 4), 2, 2690118237040, numpy.ndarray)

In [12]:
b.shape, b.ndim, id(b), type(b)

((3, 4), 2, 2690118237040, numpy.ndarray)

In [13]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
# a와 b가 같아짐

## 4.2 얕은 복사 : 뷰(View)
- 깊은 복사는 데이터와 틀 모두를 복사
- 얕은 복사는 틀만 복사

In [16]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
a.reshape(2, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [19]:
c = a.view() #얕은 복사
print(id(a), id(c))

2690145529232 2690145529520


In [20]:
c==a

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [22]:
c.shape = 2,6
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [24]:
a #a틀은 바꾼 게 아니라 그대로.

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
c[1, ::2] = [9,9,9]
c #데이터를 바꿈

array([[ 0,  1,  2,  3,  4,  5],
       [ 9,  7,  9,  9,  9, 11]])

In [28]:
a #a의 틀은 역시 그대로

array([[ 0,  1,  2,  3],
       [ 4,  5,  9,  7],
       [ 9,  9,  9, 11]])

In [29]:
c[1, ::2] = -99 #1행의 짝수번째 열 변경(9)
c

array([[  0,   1,   2,   3,   4,   5],
       [-99,   7, -99,   9, -99,  11]])

In [30]:
a

array([[  0,   1,   2,   3],
       [  4,   5, -99,   7],
       [-99,   9, -99,  11]])

## 4.3 깊은 복사

In [48]:
a = np.array([[5,  4, 13, 0],
              [99, 6, 16, 1],
              [20, 5, 14, 0],])
a

array([[ 5,  4, 13,  0],
       [99,  6, 16,  1],
       [20,  5, 14,  0]])

In [49]:
# X = a[:, :-1] #슬라이싱이 될 때, 뷰가 반환됨(얕은 복사)
X = a[:, :-1].copy() #깊은복사
X = np.array(a[:,:-1], copy=True) #깊은복사
X

array([[ 5,  4, 13],
       [99,  6, 16],
       [20,  5, 14]])

In [50]:
X[:, 0] = -9
X

array([[-9,  4, 13],
       [-9,  6, 16],
       [-9,  5, 14]])

In [52]:
a #X를 바꿨으나 a는 그대로

array([[ 5,  4, 13,  0],
       [99,  6, 16,  1],
       [20,  5, 14,  0]])

# 5절. 고급인덱싱